// vue-coin/src/components/list/Table.vue
<template>
    <div class="Table-container">
        <table class="Table">
            <thead class="Table-head">
                <tr>
                    <th>Cryptocurrency</th>
                    <th>Price</th>
                    <th>Market Cap</th>
                    <th>24H Change</th>
                </tr>
            </thead>
            <tbody class="Table-body">
                <tr v-for="currency in currencies" :key="currency.id">
                    <td>
                        <span class="Table-rank">{{currency.rank}}</span>
                        {{currency.name}}
                    </td>
                    <td>
                        <span class="Table-dollar">$</span>
                        {{currency.price}}
                    </td>
                    <td>
                        <span class="Table-dollar">$</span>
                        {{currency.marketCap}}
                    </td>
                    <td>
                        <PercentChange :percent="currency.percentChange24h"/>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<script>
import PercentChange from '../common/PercentChange.vue';

export default {
    components: {
        PercentChange,
    },
    props: {
        currencies: {
            type: Array,
            required: true,
        }
    }
}
</script>

<style>
.Table-container {
  overflow-x: auto; /* Needed for table to be responsive */
}

.Table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
}

.Table-head {
  background-color: #0c2033;
}

.Table-head tr th {
  padding: 10px 20px;
  color: #9cb3c9;
  text-align: left;
  font-size: 14px;
  font-weight: 400;
}

.Table-body {
  text-align: left;
  background-color: #0f273d;
}

.Table-body tr td {
  padding: 24px 20px;
  border-bottom: 2px solid #0c2033;
  color: #fff;
  cursor: pointer;
}

.Table-rank {
  color: #9cb3c9;
  margin-right: 18px;
  font-size: 12px;
}

.Table-dollar {
  color: #9cb3c9;
  margin-right: 6px;
}

</style>

// react-coin/src/components/list/Table.js
import React from 'react';
import PropTypes from 'prop-types';
import './Table.css';

const Table = (props) => {
    const { currencies, renderChangePercent } = props;

    return (
        <div className="Table-container">
            <table className="Table">
                <thead className="Table-head">
                    <tr>
                        <th>Cryptocurrency</th>
                        <th>Price</th>
                        <th>Market Cap</th>
                        <th>24H Change</th>
                    </tr>
                </thead>
                <tbody className="Table-body">
                {currencies.map(currency => (
                    <tr key={currency.id}>
                        <td>
                            <span className="Table-rank">{currency.rank}</span>
                            {currency.name}
                        </td>
                        <td>
                            <span className="Table-dollar">$</span>
                            {currency.price}
                        </td>
                        <td>
                            <span className="Table-dollar">$</span>
                            {currency.marketCap}
                        </td>
                        <td>
                            {renderChangePercent(currency.percentChange24h)}
                        </td>
                    </tr>
                ))}
                </tbody>
            </table>
        </div>
    );
}

Table.propTypes = {
    currencies: PropTypes.array.isRequired,
    renderChangePercent: PropTypes.func.isRequired,
}

export default Table;
