// react-coin/src/components/common/Header.js
import React from 'react';
import { Link } from 'react-router-dom';
import Search from './Search';
import logo from './logo.png';
import './Header.css';

const Header = () => {
    return (
        <div className="Header">
            <Link to="/">
                <img src={logo} alt="logo" className="Header-logo"/>
            </Link>

            <Search/>
        </div>
    );
}

export default Header;

// vue-coin/src/components/common/Header.vue
<template>
    <div class="Header">
      <router-link to="/">
        <img src="./logo.png" alt="logo" class="Header-logo"/>
      </router-link>

      <Search/>
    </div>
</template>

<script>
import Search from './Search';

export default {
  components: {
    Search
  }
}
</script>

<style>
.Header {
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  background-color: #0f273d;
  width: 100%;
  height: 80px;
}

.Header-logo {
  position: absolute;
  top: 30px;
  left: 20px;
  width: 90px;
}

@media (max-width: 700px) {
  .Header-logo {
    display: none;
  }
}
</style>
