// react-coin/src/components/detail/Detail.js
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { API_URL } from '../../config';
import { handleResponse, renderChangePercent, displayLocaleNumber, usePrevious } from '../../helpers';
import Loading from '../common/Loading';
import './Detail.css';

const Detail = () => {
    const [state, setState] = useState({
        currency: {},
        loading: false,
        error: null,
    });
    const { loading, error, currency } = state;
    const params = useParams();
    const currencyId = params.id;
    const prevCurrencyId = usePrevious(currencyId);

    const fetchCurrency = (currencyId) => {
        setState({ loading: true, error: null });

        fetch(`${API_URL}/coins/${currencyId}?localization=false&tickers=false&market_data=true&community_data=false&developer_data=false&sparkline=false`)
        .then(handleResponse)
        .then(currency => {
            setState({
                loading: false,
                currency,
            })
        })
        .catch(error => {
            setState({
                loading: false,
                error: error.errorMessage,
            })
        });
    }

    useEffect(() => {
        if(prevCurrencyId !== currencyId)
            fetchCurrency(currencyId);
    }, [prevCurrencyId, currencyId]);


    if (loading) {
        return <div className="loading-container"><Loading/></div>
    }

    if (error) {
        return <div className="error">{error}</div>
    }

    if (currency.name === undefined) {
        return <div></div>
    }

    return (
        <div className="Detail">
            <h1 className="Detail-heading">
                {currency.name} ({currency.symbol})
            </h1>

            <div className="Detail-container">
                <div className="Detail-item">
                    Price <span className="Detail-value">$ {displayLocaleNumber(currency.market_data.current_price.usd)}</span>
                </div>
                <div className="Detail-item">
                    Rank <span className="Detail-value">{currency.market_data.market_cap_rank}</span>
                </div>
                <div className="Detail-item">
                    24H Change <span className="Detail-value">{renderChangePercent(currency.market_data.price_change_percentage_24h)}</span>
                </div>
                <div className="Detail-item">
                    <span className="Detail-title">Market cap</span>
                    <span className="Detail-dollar">$</span>
                    {displayLocaleNumber(currency.market_data.market_cap.usd)}
                </div>
                <div className="Detail-item">
                    <span className="Detail-title">Volume</span>
                    <span className="Detail-dollar">$</span>
                    {displayLocaleNumber(currency.market_data.total_volume.usd)}
                </div>
                <div className="Detail-item">
                    <span className="Detail-title">Total supply</span>
                    {displayLocaleNumber(currency.market_data.total_supply)}
                </div>
            </div>
        </div>
    );

}

export default Detail;

// vue-coin/src/components/detail/Detail.vue
<template>
    <div>
        <div v-if="loading" class="loading-container"><Loading/></div>
        <div v-else-if="error" class="error">{{error}}</div>
        <div v-else class="Detail">
            <h1 class="Detail-heading">{{currency.name}} ({{currency.symbol}})</h1>

            <div class="Detail-container">
                <div class="Detail-item">
                    Price <span class="Detail-value">$ {{displayNumber(currency.market_data.current_price.usd)}}</span>
                </div>
                <div class="Detail-item">
                    Rank <span class="Detail-value">{{currency.market_data.market_cap_rank}}</span>
                </div>
                <div class="Detail-item">
                    24H Change <span class="Detail-value"><PercentChange :percent="currency.market_data.price_change_percentage_24h"/></span>
                </div>
                <div class="Detail-item">
                    <span class="Detail-title">Market cap</span>
                    <span class="Detail-dollar">$</span>{{displayNumber(currency.market_data.market_cap.usd) }}
                </div>
                <div class="Detail-item">
                    <span class="Detail-title">Volume</span>
                    <span class="Detail-dollar">$</span>{{displayNumber(currency.market_data.total_volume.usd)}}
                </div>
                <div class="Detail-item">
                    <span class="Detail-title">Total supply</span>{{displayNumber(currency.market_data.total_supply)}}
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import Loading from '../common/Loading.vue';
import PercentChange from '../common/PercentChange.vue';
import { API_URL } from '../../config';
import { handleResponse, displayLocaleNumber } from '../../helpers';

export default {
    components: {
        Loading,
        PercentChange,
    },
    data: function() {
        return {
            currency: {},
            loading: false,
            error: null,
        }
    },
    props: {
        id: {
            type: String,
            required: true,
        }
    },
    methods: {
        fetchCurrency: function(currencyId) {
            this.loading = true;
            this.error = null;

            fetch(`${API_URL}/coins/${currencyId}?localization=false&tickers=false&market_data=true&community_data=false&developer_data=false&sparkline=false`)
            .then(handleResponse)
            .then(currency => {
                this.loading = false;
                this.currency = currency;
            })
            .catch(error => {
                this.loading = false,
                this.error = error.errorMessage;
            })
        },
        displayNumber: function(value) {
            return displayLocaleNumber(value);
        }
    },
    watch: {
        id: function() {
            this.fetchCurrency(this.id);
        }
    },
    beforeMount: function() {
        this.fetchCurrency(this.id);
    }
}
</script>

<style>
.Detail {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 30px;
  margin-bottom: 40px;
  padding: 0 60px;
}

.Detail-heading {
  font-size: 24px;
  font-weight: 300;
}

.Detail-container {
  width: 100%;
  max-width: 400px;
  margin-top: 30px;
  padding: 40px 40px 0;
  border-radius: 4px;
  box-shadow: 0px 0px 40px 0px#1F4D1F;
}

.Detail-item {
  margin-bottom: 50px;
}

.Detail-value {
  border-radius: 20px;
  background-color: #1F4D1F;
  font-size: 14px;
  padding: 8px 12px;
  margin-left: 10px;
}

.Detail-title {
  display: block;
  color: #9CC99C;
  font-size: 12px;
  font-weight: bold;
  margin-bottom: 10px;
}

.Detail-dollar {
  color: #9CC99C;
  margin-right: 6px;
}
</style>
